name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup variables
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install cmake python3 build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.17.x"
      - name: Use cmake
        run: cmake --version
      
      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          ref: 2.1.0
          submodules: recursive

      - name: Set SDK path
        run: echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Build Firmware
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/pico_ble_keyboard_adapter.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
